// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoAJiXMEsErEIktprKfsBuw9fOjOBokRI',
    appId: '1:849106193757:web:42a7ff8fd4ac62ba332cb4',
    messagingSenderId: '849106193757',
    projectId: 'flutter-notes-app-1f2d1',
    authDomain: 'flutter-notes-app-1f2d1.firebaseapp.com',
    storageBucket: 'flutter-notes-app-1f2d1.firebasestorage.app',
    measurementId: 'G-DYKNJJMHXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZ_EOxxQAnSbBWnqsPzl5jGdO6QO2ikM',
    appId: '1:849106193757:android:e9952a0183d8bd39332cb4',
    messagingSenderId: '849106193757',
    projectId: 'flutter-notes-app-1f2d1',
    storageBucket: 'flutter-notes-app-1f2d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOHvtVBQXTOedoHhCRf4xOa7fr8odzqiw',
    appId: '1:849106193757:ios:08e6f189fc9af69b332cb4',
    messagingSenderId: '849106193757',
    projectId: 'flutter-notes-app-1f2d1',
    storageBucket: 'flutter-notes-app-1f2d1.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOHvtVBQXTOedoHhCRf4xOa7fr8odzqiw',
    appId: '1:849106193757:ios:08e6f189fc9af69b332cb4',
    messagingSenderId: '849106193757',
    projectId: 'flutter-notes-app-1f2d1',
    storageBucket: 'flutter-notes-app-1f2d1.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoAJiXMEsErEIktprKfsBuw9fOjOBokRI',
    appId: '1:849106193757:web:fd0da25d144a05ed332cb4',
    messagingSenderId: '849106193757',
    projectId: 'flutter-notes-app-1f2d1',
    authDomain: 'flutter-notes-app-1f2d1.firebaseapp.com',
    storageBucket: 'flutter-notes-app-1f2d1.firebasestorage.app',
    measurementId: 'G-39CT70ZMJP',
  );
}
